/*
stream-chat-react is the official react sdk for Stream Chat for building chat applications

A hook is a special function that helps you add React features to function components on the fly instead of 
    useState Hook - allows us to track state in a function component 
    useEffect Hook - allows us to perform side effects to our components e.g fetching data, directly updating the DOM by checking the dependency values
    useContext Hook- is used to create common data that can be accessed throughout the component hierarchy without passing the props down manually to each level    

Axios is a JavaScript Library used to make HTTP requests from node.js or XMLHttpRequests from the browser and it supports the Promise API that is native to JS ES6.
Unlike fetch() it supports XSRF(Cross-site request forgery, which is a type of malicious exploit of a website where unauthorized commands are submitted from a user
that the web application trusts) by a CRSF token which is a unique, secret, unpredicatable value that is generated by the server-side application
and transmitted to the client in such a way that it is included in a subsequent HTTP request made by the client.
 */